// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: monitor_file.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileAttrAttributes int32

const (
	FileAttr_HIDDEN    FileAttrAttributes = 0
	FileAttr_READONLY  FileAttrAttributes = 1
	FileAttr_READWRITE FileAttrAttributes = 3
)

// Enum value maps for FileAttrAttributes.
var (
	FileAttrAttributes_name = map[int32]string{
		0: "HIDDEN",
		1: "READONLY",
		3: "READWRITE",
	}
	FileAttrAttributes_value = map[string]int32{
		"HIDDEN":    0,
		"READONLY":  1,
		"READWRITE": 3,
	}
)

func (x FileAttrAttributes) Enum() *FileAttrAttributes {
	p := new(FileAttrAttributes)
	*p = x
	return p
}

func (x FileAttrAttributes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileAttrAttributes) Descriptor() protoreflect.EnumDescriptor {
	return file_monitor_file_proto_enumTypes[0].Descriptor()
}

func (FileAttrAttributes) Type() protoreflect.EnumType {
	return &file_monitor_file_proto_enumTypes[0]
}

func (x FileAttrAttributes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileAttrAttributes.Descriptor instead.
func (FileAttrAttributes) EnumDescriptor() ([]byte, []int) {
	return file_monitor_file_proto_rawDescGZIP(), []int{0, 0}
}

type FileAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path       string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type       string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Size       int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AccessedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=accessed_at,json=accessedAt,proto3" json:"accessed_at,omitempty"`
	ModifiedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	Content    string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *FileAttr) Reset() {
	*x = FileAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_monitor_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAttr) ProtoMessage() {}

func (x *FileAttr) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAttr.ProtoReflect.Descriptor instead.
func (*FileAttr) Descriptor() ([]byte, []int) {
	return file_monitor_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileAttr) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileAttr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileAttr) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FileAttr) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileAttr) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FileAttr) GetAccessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessedAt
	}
	return nil
}

func (x *FileAttr) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *FileAttr) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_monitor_file_proto protoreflect.FileDescriptor

var file_monitor_file_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe0, 0x02, 0x0a, 0x08,
	0x46, 0x69, 0x6c, 0x65, 0x41, 0x74, 0x74, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x3b, 0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x41, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x35, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x49, 0x44, 0x44, 0x45, 0x4e, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x41, 0x44, 0x4f, 0x4e, 0x4c, 0x59, 0x10, 0x01, 0x12,
	0x0d, 0x0a, 0x09, 0x52, 0x45, 0x41, 0x44, 0x57, 0x52, 0x49, 0x54, 0x45, 0x10, 0x03, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_monitor_file_proto_rawDescOnce sync.Once
	file_monitor_file_proto_rawDescData = file_monitor_file_proto_rawDesc
)

func file_monitor_file_proto_rawDescGZIP() []byte {
	file_monitor_file_proto_rawDescOnce.Do(func() {
		file_monitor_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_monitor_file_proto_rawDescData)
	})
	return file_monitor_file_proto_rawDescData
}

var file_monitor_file_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_monitor_file_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_monitor_file_proto_goTypes = []any{
	(FileAttrAttributes)(0),       // 0: filesystem_discovery.FileAttr.attributes
	(*FileAttr)(nil),              // 1: filesystem_discovery.FileAttr
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_monitor_file_proto_depIdxs = []int32{
	2, // 0: filesystem_discovery.FileAttr.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: filesystem_discovery.FileAttr.accessed_at:type_name -> google.protobuf.Timestamp
	2, // 2: filesystem_discovery.FileAttr.modified_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_monitor_file_proto_init() }
func file_monitor_file_proto_init() {
	if File_monitor_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_monitor_file_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FileAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_monitor_file_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_monitor_file_proto_goTypes,
		DependencyIndexes: file_monitor_file_proto_depIdxs,
		EnumInfos:         file_monitor_file_proto_enumTypes,
		MessageInfos:      file_monitor_file_proto_msgTypes,
	}.Build()
	File_monitor_file_proto = out.File
	file_monitor_file_proto_rawDesc = nil
	file_monitor_file_proto_goTypes = nil
	file_monitor_file_proto_depIdxs = nil
}
